name: Test lookup.json changes

on:
  push:
    branches:
      - master
    paths:
      - lib/lookup.json
  pull_request:
    paths:
      - lib/lookup.json

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }} and ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Link citgm globally
          run: npm link
        - name: Run smoker on changed modules
          # TODO: find lines that changed in the lookup and run
          # citgm-all --includeTags module1 module2
